# Main
main.name = "${PWNAGOTCHI_NAME}"
main.lang = "${PWNAGOTCHI_LANG}"
main.iface = "${PWNAGOTCHI_IFACE_MON}"
main.mon_max_blind_epochs = ${PWNAGOTCHI_MAX_BLIND_EPOCHS}
main.whitelist = ${PWNAGOTCHI_WHITELIST}
main.filter = "${PWNAGOTCHI_FILTER}"
main.custom_plugins = "/usr/local/lib/pwnagotchi/plugins/"

# Logs
main.log.path = "" # Print only to console
main.log.rotation.enabled = false

# Grid plugin
main.plugins.grid.enabled = ${PWNAGOTCHI_PLUGIN_GRID_ENABLED}
main.plugins.grid.report = ${PWNAGOTCHI_PLUGIN_GRID_REPORT}
main.plugins.grid.exclude = ${PWNAGOTCHI_PLUGIN_GRID_EXCLUDE}

# Led plugin
main.plugins.led.enabled = ${PWNAGOTCHI_PLUGIN_LED_ENABLED}

# Memtemp plugin
main.plugins.memtemp.enabled = ${PWNAGOTCHI_PLUGIN_MEMTEMP_ENABLED}

# Session stats plugin
main.plugins.session-stats.enabled = ${PWNAGOTCHI_PLUGIN_SESSION_STATS_ENABLED}

# Auto update plugin
main.plugins.auto-update.enabled = false

# Webcfg plugin
main.plugins.webcfg.enabled = false

# Web UI
ui.web.enabled = ${PWNAGOTCHI_WEB_ENABLED}
ui.web.address = "${PWNAGOTCHI_WEB_ADDRESS}"
ui.web.username = "${PWNAGOTCHI_USERNAME}"
ui.web.password = "${PWNAGOTCHI_PASSWORD}"

# Display UI
ui.display.enabled = ${PWNAGOTCHI_DISPLAY_ENABLED}
ui.display.rotation = ${PWNAGOTCHI_DISPLAY_ROTATION}
ui.display.type = "${PWNAGOTCHI_DISPLAY_TYPE}"

# Bettercap
bettercap.username = "${PWNAGOTCHI_USERNAME}"
bettercap.password = "${PWNAGOTCHI_PASSWORD}"

# Personality
personality.advertise = ${PWNAGOTCHI_PERSONALITY_ADVERTISE}
personality.deauth = ${PWNAGOTCHI_PERSONALITY_DEAUTH}
personality.associate = ${PWNAGOTCHI_PERSONALITY_ASSOCIATE}
personality.channels = ${PWNAGOTCHI_PERSONALITY_CHANNELS}


# Bluetooth
main.plugins.bt-tether.enabled = true
main.plugins.bt-tether.devices.android-phone.enabled = true          # the name of this entry is android-phone
main.plugins.bt-tether.devices.android-phone.search_order = 1         # in which order the devices should
                                                                      ## be searched. E.g. this is #1
main.plugins.bt-tether.devices.android-phone.mac = "${PWNAGOTCHI_ANDROID_MAC}"                 # you need to put your phones
                                                                      ## bt-mac here (settings > status)
main.plugins.bt-tether.devices.android-phone.ip = "${PWNAGOTCHI_ANDROID_IP}"     # this is the static ip of your pwnagotchi
                                                                      ## adjust this to your phones pan-network
                                                                      ## (run "ifconfig bt-pan" on your phone)
                                                                      ## if you feel lucky,
                                                                      ## try: 192.168.44.44 (Android) or
                                                                      ## 172.20.10.6 (iOS)
                                                                      ## 44 is just an example, you can choose
                                                                      ## between 2-254 (if netmask is 24)
main.plugins.bt-tether.devices.android-phone.netmask = 24             # netmask of the PAN
main.plugins.bt-tether.devices.android-phone.interval = 1             # in minues, how often should
                                                                      ## the device be searched
main.plugins.bt-tether.devices.android-phone.scantime = 10            # in seconds, how long should be searched
                                                                      ## on each interval
main.plugins.bt-tether.devices.android-phone.max_tries = 30           # how many times it should try to find the
                                                                      ## phone (0 = endless)
main.plugins.bt-tether.devices.android-phone.share_internet = true   # set to true if you want to have
                                                                      ## internet via bluetooth
main.plugins.bt-tether.devices.android-phone.priority = 1             # the device with the highest
                                                                     ## priority wins (1 = highest)

main.plugins.quickdic.enabled = ${PWNAGOTCHI_QUICKDIC_ENABLED}
main.plugins.quickdic.wordlist_folder = "/opt/wordlists/"

main.plugins.aircrackonly.enabled = true
main.plugins.hashie.enabled = true

main.plugins.onlinehashcrack.enabled = ${PWNAGOTCHI_ONLINEHASHCRACK_ENABLED}
main.plugins.onlinehashcrack.email = "${PWNAGOTCHI_ONLINEHASHCRACK_EMAIL}"
main.plugins.onlinehashcrack.dashboard = ""
main.plugins.onlinehashcrack.single_files = false
main.plugins.onlinehashcrack.whitelist = []

main.plugins.wpa-sec.enabled = ${PWNAGOTCHI_WPASEC_ENABLED}
main.plugins.wpa-sec.api_key = "${PWNAGOTCHI_WPASEC_API_KEY}"
main.plugins.wpa-sec.api_url = "https://wpa-sec.stanev.org"
main.plugins.wpa-sec.download_results = true
main.plugins.wpa-sec.whitelist = []

main.plugins.webgpsmap.enabled = ${PWNAGOTCHI_WEBGPSMAP_ENABLED}
main.plugins.paw-gps.enabled = ${PWNAGOTCHI_PAW_GPS_ENABLED}
main.plugins.paw-gps.ip = "192.168.44.1:8080"

main.plugins.ups_lite.enabled = ${PWNAGOTCHI_UPS_LITE_ENABLED}

main.plugins.pisugar2.enabled = ${PWNAGOTCHI_PISUGAR_ENABLED}
main.plugins.pisugar2.shutdown = 3
main.plugins.pisugar2.sync_rtc_on_boot = true

main.plugins.exp.enabled = ${PWNAGOTCHI_PLUGIN_EXPERIENCE_ENABLED}
main.plugins.exp.lvl_x_coord = 0
main.plugins.exp.lvl_y_coord = 81
main.plugins.exp.exp_x_coord = 38
main.plugins.exp.exp_y_coord = 81
main.plugins.exp.bar_symbols_count = 12
